### ISSUE TITLE
What does this item mean? Is it resurrected KIVY designer?

### ISSUE THREAD

**Issue by ChinaGodzilla** [Heitor-Tasso/KivyStudioDesigner#3]
What does this item mean? Is it resurrected KIVY designer?

**Comment by Heitor-Tasso** [comment]
Yeah! I'm working in more than one project. KivyStudioDesigner will use some part of [KivyMaker](https://github.com/Heitor-Tasso/KivyMaker) and the UI will be made with a library named [KivyGO](https://github.com/Heitor-Tasso/kivygo).

It's in progress. I'm having a lot of work to do that because i'm working alone for now...
